# -*- coding: utf-8 -*-
"""AI-Personal-Sports-Trainer .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pZH0VD0bO1tUuQVgL4I-GchxmUAt9sVQ
"""

!pip install crewai openai langchain_openai -q

!pip install crewai -q

from crewai import Agent, Task, Crew
from langchain_openai import ChatOpenAI

!pip install langchain_openai -q

import os
os.environ["OPENAI_API_KEY"]=""

llm = ChatOpenAI(model='gpt-4o-mini')


career_coach = Agent(
    role=" Fitness Career Coach",
    goal="Suggest a suitable fitness specialization for a user interested in health or training , such as personal training, nutrition, or flexibility coaching",
    backstory="You are a professional fitness expert who helps beginners find the best career bath in fitness and health.",
    llm=llm
)


motivation_coach = Agent(
    role="Motivation trainer ",
    goal="Inspire the user with an encouraging message and suggest a realistic first action step.",
    backstory="You are a motivational trainer who helps people stay committed to their goals and start with confidence.",
    llm=llm
)



resource_finder = Agent(
    role="Fitness Learning Advisor",
    goal="Find 1–2 beginner-friendly resources (YouTube, blogs, or online courses) to help the user learn fitness basics.",
    backstory="You are a research professional who knows the best online resources for beginners in sports and fitness.",
    llm=llm
)



supervisor = Agent(
    role="Program Supervisor",
    goal="Combine all outputs from the other agents into one clear final message summarizing the fitness path, motivation, and resources",
    backstory="You are a wise supervisor from a fitness academy who merges advice and motivation into one inspiring report.",
    llm=llm
)

interest = input("🏋️‍♀️ What is your fitness goal or area of interest? ")


# Task 1 - Career suggestion
task1 = Task(
    description=f"Suggest a fitness specialization that fits a person interested in {interest}. Give one reason why it suits them",
    expected_output="Specialization name and 1–2 lines of explanation..",
    agent=career_coach
)


# Task 2 - Motivation message
task2 = Task(
    description="Give a short motivational message and suggest one first practical step to start in the fitness field.",
    expected_output="1 quote/message + 1 action step.",
    agent=motivation_coach,
    depends_on=[task1]
)


# Task 3 - Learning resources
task3 = Task(
    description="Find 1–2 beginner-friendly resources (YouTube channels, blogs, or courses) related to the suggested fitness specialization.",
    expected_output="List of 1–2 short links or descriptions.",
    agent=resource_finder,
    depends_on=[task1]
)


# Task 4 - Supervisor final summary
task4 = Task(
    description="Combine all previous outputs and write a 5–6 line summary that includes the fitness specialization, motivation, and resources.",
    expected_output="Final integrated summary.",
    agent=supervisor,
    depends_on=[task1, task2, task3]
)

crew = Crew(
    agents=[career_coach, motivation_coach, resource_finder, supervisor],
    tasks=[task1, task2, task3, task4]
)
result = crew.kickoff()
print(result)